"""Problem 2
19 October 2001

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
a, b, fib = 1, 2, []
while a <= 4000000:
    fib.append(a)
    a, b = b, a + b
Prob2 = sum([x for x in fib if x % 2 == 0])
print "Problem 2: %i" % Prob2
